#!/bin/bash

VPN_EXEC="/opt/cisco/anyconnect/bin/vpn"
VPN_PREF="$HOME/.anyconnect"
VPN_PASS="$HOME/.anyconnect_pass"

# Read user name from AnyConnect preferences
HOST=$(cat $VPN_PREF | grep DefaultHostName)
HOST=${HOST/<DefaultHostName>/}
HOST=${HOST/<\/DefaultHostName>}
USERNAME=$(cat $VPN_PREF | grep DefaultUser)
USERNAME=${USERNAME/<DefaultUser>/}
USERNAME=${USERNAME/<\/DefaultUser>/}
PASSWORD=$(cat $HOME/.anyconnect_pass)

OPTIND=1 

while getopts "cdshp:" opt; do
  case "$opt" in
  c)
    printf "$USERNAME\n$PASSWORD\ny" | $VPN_EXEC -s connect $HOST
    exit 0
    ;;
  d) 
    $VPN_EXEC disconnect
    exit 0 
    ;;
  s) 
    $VPN_EXEC status
    exit 0
    ;;
  h) 
    $VPN_EXEC hosts
    exit 0
    ;;
  p) 
    echo $OPTARG > $VPN_PASS
  esac
done

